### PR TITLE
hyphen->underscore, added setup & file io, edited README

### PR DESCRIPTION
**Pull request by drscotthawley**

### CODE REVIEW

**Comment by hagenw** [comment]
Thanks for submitting your pull request.

In order to better review pull request and accept or reject certain features, it would be great if could split up the current pull request into several ones covering only one topic, e.g.
*  Remove whitespace from README
* Add `setup.py` and installation instruction to README
*  Add proposal for loading audio files

**Comment by keunwoochoi** [comment]
Hi @drscotthawley :)
Thanks for the PR. As @hagenw said I think it'd be better to be split into different PRs not only because that's encouraged in general but also I think we probably would like to partially merge your current PR.
We're a bit concerned about packaging it because we want this repo to be a base camp where things are collaborated to make PRs to the original torch/audio repo with consensus, therefore, packaging it could be nice, we'd rather keep it simple, just a bunch of codes with a loose definition of 'version'. 

That said, we think it makes sense to change the folder name. I haven't looked into the audio reading part but am sure @faroit would review for a separate PR if you can make one.

**Comment by drscotthawley** [comment]
Hey guys. That makes sense.   

I did actually submit multiple PRs, but GitHub has somehow bundled them all together into one.   (In fact, I've had another GitHub community say they prefer it this way.)  

I'm not sure how to disable this "bundling" process, but I can try again.  This PR will probably get automatically closed in the process.  If not, I'll close it when/if my new submissions get counted as separate.

**Comment by keunwoochoi** [comment]
Thanks!

**Comment by drscotthawley** [comment]
Wait...ok, so apparently to avoid having multiple changes accumulating in one PR, I have to create a different branch for every separate PR I want to send. 
It's easier if I delete my fork and start over, which will necessarily close this PR.

**Pull request closed without merging**
